### ISSUE TITLE
Document permissions required for Github app

### ISSUE THREAD

**Issue by ievans** [returntocorp/semgrep-docs#133]
please add a breakdown of each semgrep permission requested and why it’s needed 

We could re-use the same copy from the app, or link / embed docs in the app:

![image](https://user-images.githubusercontent.com/409041/111517592-3a7fef00-8723-11eb-81d7-2fbaeadf7c3f.png)

**Comment by dlukeomalley** [comment]
@ievans Clarifying questions for us to prioritize:

1. What outcome are you after? Could we rephrase this ticket as something like "New Semgrep App users know why each GitHub permission is requested"?
2. What priority is this? Is this need coming from a specific customer (if so, can add to Customer board) otherwise we'll queue it up as part of a normal sprint.
3. Is there any evidence this is an acute issue vs. an enhancement? Anecdotally watching FullStory recordings people don't get hung up on this page.

**Comment by adamkvitek** [comment]
Covered by docs provided from @s-santillan. Closing the issue.
