### ISSUE TITLE
Sidebar always thinks I'm in the "Writing rules" section

### ISSUE THREAD

**Issue by underyx** [returntocorp/semgrep-docs#68]
<img width="672" alt="Screen Shot 2020-12-14 at 15 08 36" src="https://user-images.githubusercontent.com/1060436/102090835-3f7c8c00-3e1e-11eb-890e-da1a7000feac.png">

After clicking on another sidebar item, it flashes correctly for a second and then resets to highlighting this.

**Comment by chmccreery** [comment]
@pabloest @dlukeomalley I wanted to bump this before launch - noticed it again today

**Comment by pabloest** [comment]
Thanks for bumping, @chmccreery. I had looked into this a little bit last year and played with something, will dig it up and see where it left off.

**Comment by pabloest** [comment]
The root cause of this behavior is related to the amount of nesting we use in the docs. We’re using more nesting levels than what is supported by [the theme](https://www.mkdocs.org/user-guide/styling-your-docs/#readthedocs).

So one fix is to reduce the amount of nesting we use in the sidebar. That would look something like this:
![Screen Shot 2021-02-01 at 4 09 18 PM](https://user-images.githubusercontent.com/302941/106534167-4f246280-64a8-11eb-9119-de361fef41f4.png)

What do you think?

**Comment by chmccreery** [comment]
I like it! The sections don't all make sense to me immediately (where would I go for Semgrep Action documentation, for example?), but otherwise I am not bothered by the lower amount of nesting.

**Comment by pabloest** [comment]
Thanks, Clara! I’ll open a PR and reference your comment, then we can continue the discussion there.
